using System;
using System.Collections.Generic;
using Roguelike.Domain.Gameplay.Maps.Entities;
using Roguelike.Domain.Gameplay.Maps.Enums;
using Roguelike.Domain.Gameplay.Maps.ValueObjects;

namespace Roguelike.Domain.Gameplay.Maps.Services
{
    /// <summary>
    /// 設計図（区域）ベースで部屋と通路を作るサービスです。
    /// </summary>
    public class MapGenerationService : IMapGenerationService
    {
        /// <summary>
        /// デフォルトの横幅。
        /// </summary>
        public const int DefaultWidth = 48;
        /// <summary>
        /// デフォルトの縦幅。
        /// </summary>
        public const int DefaultHeight = 48;

        // 生成パラメータ（バランス調整用の固定値）。
        private const int DefaultMinRooms = 6; // 部屋の最小数。
        private const int DefaultMaxRooms = 10; // 部屋の最大数。
        private const int DefaultMinRoomSize = 4; // 部屋の最小幅/高さ。
        private const int DefaultMaxRoomSize = 10; // 部屋の最大幅/高さ。
        private const int DefaultMinRandomBranches = 1; // 追加通路の最小数。
        private const int DefaultMaxRandomBranches = 2; // 追加通路の最大数。
        private const int SectionInnerPadding = 2; // 区域内で部屋を作る際の内側余白。
        private const int OuterPadding = 1; // 外周に余白を持たせるためのパディング。

        /// <summary>
        /// デフォルトの大きさでマップを作ります。
        /// </summary>
        public Map Generate(int seed)
        {
            return Generate(DefaultWidth, DefaultHeight, seed);
        }

        /// <summary>
        /// 指定サイズでマップを作ります。
        /// </summary>
        public Map Generate(int width, int height, int seed)
        {
            var map = new Map(width, height);
            var random = new Random(seed);

            // 設計図を作り、そこから区域情報を展開する。
            var blueprint = CreateBlueprint(width, height, random);
            var sections = BuildSections(blueprint);
            var rooms = new List<MapRect>();

            // 部屋を作る（強制部屋 → 重み抽選）。
            CreateRooms(blueprint, sections, rooms, random);
            if (rooms.Count == 0)
            {
                // 失敗時の保険で最低1部屋を確保する。
                rooms.Add(CreateFallbackRoom(width, height));
            }

            // 部屋がない区域には中継点を作る。
            CreateRelays(sections, random);

            // 部屋の床を掘る。
            CarveRooms(map, rooms);

            // 区域の接続情報を作り、通路を掘る。
            var connections = BuildConnections(blueprint, sections, random);
            CarveCorridors(map, sections, connections, random);

            // 部屋一覧をマップへ登録する。
            map.SetRooms(rooms);

            // スタート地点は最初の部屋の中心にする。
            var start = rooms[0].Center;
            map.SetStartPosition(start);

            // スタートから離れた地点に階段を置く。
            var stairs = FindFarthestWalkable(map, start, rooms);
            map.SetStairsDownPosition(stairs);

            return map;
        }

        // 区域同士の接続方向を示す簡易方角。
        private enum Direction
        {
            North,
            South,
            West,
            East,
        }

        // 生成に使う設計図データ（区域定義と接続情報の集合）。
        private sealed class MapBlueprint
        {
            // 生成時の部屋数と接続数の範囲。
            public int MinRooms { get; }
            public int MaxRooms { get; }
            public int MinRandomBranches { get; }
            public int MaxRandomBranches { get; }
            // 接続情報を自動生成するかどうか。
            public bool AutoGenerateDefaultConnections { get; }
            // 区域と接続の定義一覧。
            public IReadOnlyList<SectionDefinition> Sections { get; }
            public IReadOnlyList<SectionConnection> Connections { get; }

            public MapBlueprint(
                int minRooms,
                int maxRooms,
                int minRandomBranches,
                int maxRandomBranches,
                bool autoGenerateDefaultConnections,
                IReadOnlyList<SectionDefinition> sections,
                IReadOnlyList<SectionConnection> connections)
            {
                MinRooms = minRooms;
                MaxRooms = maxRooms;
                MinRandomBranches = minRandomBranches;
                MaxRandomBranches = maxRandomBranches;
                AutoGenerateDefaultConnections = autoGenerateDefaultConnections;
                Sections = sections;
                Connections = connections;
            }
        }

        // 区域（矩形領域）とその部屋生成ルールの定義。
        private sealed class SectionDefinition
        {
            public int Index { get; }
            public MapRect Bounds { get; }
            public int MinRoomSize { get; }
            public bool ForceRoom { get; }
            public int Weight { get; }
            public bool Active { get; }

            public SectionDefinition(int index, MapRect bounds, int minRoomSize, bool forceRoom, int weight, bool active)
            {
                Index = index;
                Bounds = bounds;
                MinRoomSize = minRoomSize;
                ForceRoom = forceRoom;
                Weight = weight;
                Active = active;
            }
        }

        // 生成中の区域状態（部屋・出口・中継点などの実体情報）。
        private sealed class SectionState
        {
            public SectionDefinition Definition { get; }
            public MapRect? Room { get; set; }
            public RoomJoints Joints { get; set; }
            public Position RelayPoint { get; set; }

            public SectionState(SectionDefinition definition)
            {
                Definition = definition;
            }
        }

        // 区域同士の接続情報（from/to のインデックス）。
        private readonly struct SectionConnection
        {
            public int From { get; }
            public int To { get; }

            public SectionConnection(int from, int to)
            {
                From = from;
                To = to;
            }
        }

        // 部屋の辺ごとの出口（通路の接続候補）。
        private sealed class RoomJoints
        {
            public List<Position> North { get; }
            public List<Position> South { get; }
            public List<Position> West { get; }
            public List<Position> East { get; }

            public RoomJoints(List<Position> north, List<Position> south, List<Position> west, List<Position> east)
            {
                North = north;
                South = south;
                West = west;
                East = east;
            }

            public Position Pop(Direction direction, Position fallback, Random random)
            {
                // 選択済み出口の重複を避けるため、リストから取り出す。
                var list = GetList(direction);
                if (list.Count == 0)
                {
                    return fallback;
                }

                var index = random.Next(list.Count);
                var position = list[index];
                list.RemoveAt(index);
                return position;
            }

            private List<Position> GetList(Direction direction)
            {
                // 方向に対応する出口リストを返す。
                switch (direction)
                {
                    case Direction.North:
                        return North;
                    case Direction.South:
                        return South;
                    case Direction.West:
                        return West;
                    default:
                        return East;
                }
            }
        }

        // マップサイズから区域分割と初期接続を決める。
        private static MapBlueprint CreateBlueprint(int width, int height, Random random)
        {
            // マップサイズに応じて分割数を切り替える。
            var columns = width >= 44 ? 4 : width >= 32 ? 3 : 2;
            var rows = height >= 44 ? 4 : height >= 32 ? 3 : 2;

            // 外周に余白を確保した内側領域を区域配置に使う。
            var innerX = OuterPadding;
            var innerY = OuterPadding;
            var innerWidth = Math.Max(1, width - OuterPadding * 2);
            var innerHeight = Math.Max(1, height - OuterPadding * 2);

            // 区域数よりも内側領域が小さい場合は余白を無効にする。
            if (innerWidth < columns || innerHeight < rows)
            {
                innerX = 0;
                innerY = 0;
                innerWidth = width;
                innerHeight = height;
            }

            var sections = new List<SectionDefinition>();
            // 中央寄り区域は部屋ができやすいように重みを高くする。
            var centerCols = new HashSet<int> { (columns - 1) / 2, columns / 2 };
            var centerRows = new HashSet<int> { (rows - 1) / 2, rows / 2 };

            var index = 0;
            for (int row = 0; row < rows; row++)
            {
                // 行単位で区域の範囲を決める。
                var y0 = innerY + row * innerHeight / rows;
                var y1 = innerY + (row + 1) * innerHeight / rows;
                var heightSpan = Math.Max(1, y1 - y0);

                for (int col = 0; col < columns; col++)
                {
                    // 列単位で区域の範囲を決める。
                    var x0 = innerX + col * innerWidth / columns;
                    var x1 = innerX + (col + 1) * innerWidth / columns;
                    var widthSpan = Math.Max(1, x1 - x0);

                    var bounds = new MapRect(x0, y0, widthSpan, heightSpan);
                    var isCenter = centerCols.Contains(col) && centerRows.Contains(row);
                    var isCorner = (col == 0 || col == columns - 1) && (row == 0 || row == rows - 1);
                    var weight = isCenter ? 4 : isCorner ? 2 : 1;

                    // 中央は必ず部屋を作る設定にする。
                    sections.Add(new SectionDefinition(
                        index,
                        bounds,
                        DefaultMinRoomSize,
                        isCenter,
                        weight,
                        true));
                    index++;
                }
            }

            // 一部の確率で「全隣接接続」を使い、格子型に寄せる。
            var useGridConnections = random.Next(0, 3) == 0;
            var connections = useGridConnections ? BuildAllAdjacentConnections(sections) : new List<SectionConnection>();

            return new MapBlueprint(
                DefaultMinRooms,
                DefaultMaxRooms,
                DefaultMinRandomBranches,
                DefaultMaxRandomBranches,
                !useGridConnections,
                sections,
                connections);
        }

        // 設計図の区域定義を生成用の状態に変換する。
        private static List<SectionState> BuildSections(MapBlueprint blueprint)
        {
            var sections = new List<SectionState>();
            foreach (var definition in blueprint.Sections)
            {
                sections.Add(new SectionState(definition));
            }

            return sections;
        }

        // 区域に部屋を割り当てる（強制部屋 → 重み抽選）。
        private static void CreateRooms(
            MapBlueprint blueprint,
            List<SectionState> sections,
            List<MapRect> rooms,
            Random random)
        {
            // アクティブな区域のみ対象にする。
            var activeSections = new List<SectionState>();
            for (int i = 0; i < sections.Count; i++)
            {
                if (sections[i].Definition.Active)
                {
                    activeSections.Add(sections[i]);
                }
            }

            if (activeSections.Count == 0)
            {
                return;
            }

            // 目標部屋数を乱数で決める。
            var targetRooms = random.Next(blueprint.MinRooms, blueprint.MaxRooms + 1);
            targetRooms = Math.Min(targetRooms, activeSections.Count);

            var forcedCount = 0;
            for (int i = 0; i < activeSections.Count; i++)
            {
                var section = activeSections[i];
                if (!section.Definition.ForceRoom)
                {
                    continue;
                }

                // 強制区域の部屋を先に作る。
                if (TryCreateRoom(section.Definition, random, out var room))
                {
                    section.Room = room;
                    section.Joints = CreateRoomJoints(room, random);
                    rooms.Add(room);
                    forcedCount++;
                }
            }

            // 強制部屋数に合わせて目標数を引き上げる。
            targetRooms = Math.Max(targetRooms, forcedCount);

            // 残りは重み抽選で区域を選び、部屋を作る。
            while (rooms.Count < targetRooms)
            {
                var candidates = new List<SectionState>();
                var totalWeight = 0;

                for (int i = 0; i < activeSections.Count; i++)
                {
                    var section = activeSections[i];
                    if (section.Room.HasValue)
                    {
                        continue;
                    }

                    var weight = Math.Max(0, section.Definition.Weight);
                    if (weight == 0)
                    {
                        continue;
                    }

                    candidates.Add(section);
                    totalWeight += weight;
                }

                if (candidates.Count == 0)
                {
                    break;
                }

                // 重みの合計から抽選して1区域を選ぶ。
                var pick = random.Next(0, totalWeight);
                SectionState selected = null;
                for (int i = 0; i < candidates.Count; i++)
                {
                    pick -= Math.Max(0, candidates[i].Definition.Weight);
                    if (pick < 0)
                    {
                        selected = candidates[i];
                        break;
                    }
                }

                if (selected == null)
                {
                    break;
                }

                if (TryCreateRoom(selected.Definition, random, out var created))
                {
                    selected.Room = created;
                    selected.Joints = CreateRoomJoints(created, random);
                    rooms.Add(created);
                }
                else
                {
                    // 部屋生成に失敗したら打ち切る。
                    break;
                }
            }
        }

        // 部屋がない区域に中継点（Relay）を設定する。
        private static void CreateRelays(List<SectionState> sections, Random random)
        {
            for (int i = 0; i < sections.Count; i++)
            {
                var section = sections[i];
                section.RelayPoint = section.Room?.Center ?? CreateRelayPoint(section.Definition.Bounds, random);
            }
        }

        // 区域内にランダムな部屋を作成する。
        private static bool TryCreateRoom(SectionDefinition section, Random random, out MapRect room)
        {
            // 区域境界の余白を確保した範囲で部屋を作る。
            var maxBounds = ShrinkRect(section.Bounds, SectionInnerPadding);
            if (maxBounds.Width <= 0 || maxBounds.Height <= 0)
            {
                room = default;
                return false;
            }

            // 部屋サイズの上下限を区域の範囲に合わせる。
            var maxWidth = Math.Min(DefaultMaxRoomSize, maxBounds.Width);
            var maxHeight = Math.Min(DefaultMaxRoomSize, maxBounds.Height);
            var minWidth = Math.Min(section.MinRoomSize, maxWidth);
            var minHeight = Math.Min(section.MinRoomSize, maxHeight);

            if (minWidth <= 0 || minHeight <= 0)
            {
                room = default;
                return false;
            }

            var roomWidth = random.Next(minWidth, maxWidth + 1);
            var roomHeight = random.Next(minHeight, maxHeight + 1);

            var maxX = maxBounds.Right - roomWidth + 1;
            var maxY = maxBounds.Bottom - roomHeight + 1;
            if (maxX < maxBounds.Left || maxY < maxBounds.Top)
            {
                room = default;
                return false;
            }

            // 区域内のランダム位置に配置する。
            var roomX = random.Next(maxBounds.Left, maxX + 1);
            var roomY = random.Next(maxBounds.Top, maxY + 1);

            room = new MapRect(roomX, roomY, roomWidth, roomHeight);
            return true;
        }

        // 区域内の中継点をランダムに選ぶ。
        private static Position CreateRelayPoint(MapRect bounds, Random random)
        {
            var inner = ShrinkRect(bounds, SectionInnerPadding);
            if (inner.Width <= 0 || inner.Height <= 0)
            {
                return bounds.Center;
            }

            var x = random.Next(inner.Left, inner.Right + 1);
            var y = random.Next(inner.Top, inner.Bottom + 1);
            return new Position(x, y);
        }

        // 部屋の各辺に出口候補（Joint）を作る。
        private static RoomJoints CreateRoomJoints(MapRect room, Random random)
        {
            // 奇数/偶数を揃えて隣接出口が続かないようにする。
            var parity = random.Next(0, 2);
            var north = CreateEdgeJoints(room, Direction.North, parity);
            var south = CreateEdgeJoints(room, Direction.South, parity);
            var west = CreateEdgeJoints(room, Direction.West, parity);
            var east = CreateEdgeJoints(room, Direction.East, parity);
            return new RoomJoints(north, south, west, east);
        }

        // 指定の辺上に出口候補を並べる（奇数/偶数で間引く）。
        private static List<Position> CreateEdgeJoints(MapRect room, Direction direction, int parity)
        {
            var joints = new List<Position>();
            if (direction == Direction.North || direction == Direction.South)
            {
                var y = direction == Direction.North ? room.Top : room.Bottom;
                var length = room.Width;
                for (int i = 0; i < length; i++)
                {
                    if (i % 2 != parity)
                    {
                        continue;
                    }

                    joints.Add(new Position(room.Left + i, y));
                }

                if (joints.Count == 0)
                {
                    // 小さい部屋で候補がない場合は中央を出口にする。
                    joints.Add(new Position(room.Center.X, y));
                }

                return joints;
            }

            var x = direction == Direction.West ? room.Left : room.Right;
            var height = room.Height;
            for (int i = 0; i < height; i++)
            {
                if (i % 2 != parity)
                {
                    continue;
                }

                joints.Add(new Position(x, room.Top + i));
            }

            if (joints.Count == 0)
            {
                // 小さい部屋で候補がない場合は中央を出口にする。
                joints.Add(new Position(x, room.Center.Y));
            }

            return joints;
        }

        // 区域同士の接続情報を構築する。
        private static List<SectionConnection> BuildConnections(
            MapBlueprint blueprint,
            List<SectionState> sections,
            Random random)
        {
            // アクティブな区域を抽出し、索引用の辞書を作る。
            var activeSections = new List<SectionState>();
            var sectionLookup = new Dictionary<int, SectionState>();
            for (int i = 0; i < sections.Count; i++)
            {
                var section = sections[i];
                sectionLookup[section.Definition.Index] = section;
                if (section.Definition.Active)
                {
                    activeSections.Add(section);
                }
            }

            // 区域の隣接関係（グラフ）を作る。
            var adjacency = BuildAdjacency(activeSections);
            var connections = new List<SectionConnection>();
            var connectionSet = new HashSet<long>();
            var connected = new HashSet<int>();

            // 設計図に固定接続があればそれを優先する。
            if (blueprint.Connections.Count > 0)
            {
                for (int i = 0; i < blueprint.Connections.Count; i++)
                {
                    var connection = blueprint.Connections[i];
                    if (!sectionLookup.ContainsKey(connection.From) || !sectionLookup.ContainsKey(connection.To))
                    {
                        continue;
                    }

                    if (!sectionLookup[connection.From].Definition.Active || !sectionLookup[connection.To].Definition.Active)
                    {
                        continue;
                    }

                    if (AddConnection(connections, connectionSet, connection.From, connection.To))
                    {
                        connected.Add(connection.From);
                        connected.Add(connection.To);
                    }
                }
            }
            else if (blueprint.AutoGenerateDefaultConnections && activeSections.Count > 0)
            {
                // 自動生成は「一筆書き」のイメージでランダムウォークする。
                var start = activeSections[random.Next(activeSections.Count)].Definition.Index;
                connected.Add(start);

                var current = start;
                while (adjacency.TryGetValue(current, out var neighbors))
                {
                    var candidates = new List<int>();
                    for (int i = 0; i < neighbors.Count; i++)
                    {
                        if (!connected.Contains(neighbors[i]))
                        {
                            candidates.Add(neighbors[i]);
                        }
                    }

                    if (candidates.Count == 0)
                    {
                        break;
                    }

                    var next = candidates[random.Next(candidates.Count)];
                    if (AddConnection(connections, connectionSet, current, next))
                    {
                        connected.Add(next);
                    }

                    current = next;
                }
            }

            // どことも繋がっていない区域があれば、既存の接続に寄せて繋ぐ。
            // 何も繋がっていない場合は起点を強制的に作る。
            if (connected.Count == 0 && activeSections.Count > 0)
            {
                connected.Add(activeSections[random.Next(activeSections.Count)].Definition.Index);
            }

            // 未接続の区域を、接続済み区域に順次つなげる。
            var progress = true;
            while (progress)
            {
                progress = false;
                for (int i = 0; i < activeSections.Count; i++)
                {
                    var index = activeSections[i].Definition.Index;
                    if (connected.Contains(index))
                    {
                        continue;
                    }

                    if (!adjacency.TryGetValue(index, out var neighbors))
                    {
                        continue;
                    }

                    var candidates = new List<int>();
                    for (int j = 0; j < neighbors.Count; j++)
                    {
                        if (connected.Contains(neighbors[j]))
                        {
                            candidates.Add(neighbors[j]);
                        }
                    }

                    if (candidates.Count == 0)
                    {
                        continue;
                    }

                    var target = candidates[random.Next(candidates.Count)];
                    if (AddConnection(connections, connectionSet, index, target))
                    {
                        connected.Add(index);
                        progress = true;
                    }
                }
            }

            // 余分な枝通路を追加して形を崩す。
            var branchCount = 0;
            if (blueprint.MaxRandomBranches >= blueprint.MinRandomBranches)
            {
                branchCount = random.Next(blueprint.MinRandomBranches, blueprint.MaxRandomBranches + 1);
            }

            var activeIndices = new List<int>();
            for (int i = 0; i < activeSections.Count; i++)
            {
                activeIndices.Add(activeSections[i].Definition.Index);
            }

            // 追加接続は回数上限を設けて無限ループを防ぐ。
            var attempts = 0;
            var maxAttempts = Math.Max(10, branchCount * 10);
            while (branchCount > 0 && attempts < maxAttempts)
            {
                attempts++;
                if (activeIndices.Count == 0)
                {
                    break;
                }

                var from = activeIndices[random.Next(activeIndices.Count)];
                if (!adjacency.TryGetValue(from, out var neighbors) || neighbors.Count == 0)
                {
                    continue;
                }

                var to = neighbors[random.Next(neighbors.Count)];
                if (AddConnection(connections, connectionSet, from, to))
                {
                    branchCount--;
                }
            }

            return connections;
        }

        // 区域の隣接リスト（無向グラフ）を作る。
        private static Dictionary<int, List<int>> BuildAdjacency(List<SectionState> sections)
        {
            var adjacency = new Dictionary<int, List<int>>();
            for (int i = 0; i < sections.Count; i++)
            {
                adjacency[sections[i].Definition.Index] = new List<int>();
            }

            for (int i = 0; i < sections.Count; i++)
            {
                var left = sections[i].Definition;
                for (int j = i + 1; j < sections.Count; j++)
                {
                    var right = sections[j].Definition;
                    if (!AreAdjacent(left.Bounds, right.Bounds))
                    {
                        continue;
                    }

                    adjacency[left.Index].Add(right.Index);
                    adjacency[right.Index].Add(left.Index);
                }
            }

            return adjacency;
        }

        // 2つの区域が辺で接しているかを判定する。
        private static bool AreAdjacent(MapRect a, MapRect b)
        {
            if (a.Right + 1 == b.Left || b.Right + 1 == a.Left)
            {
                return RangesOverlap(a.Top, a.Bottom, b.Top, b.Bottom);
            }

            if (a.Bottom + 1 == b.Top || b.Bottom + 1 == a.Top)
            {
                return RangesOverlap(a.Left, a.Right, b.Left, b.Right);
            }

            return false;
        }

        // 重複しない接続だけを追加する。
        private static bool AddConnection(
            List<SectionConnection> connections,
            HashSet<long> connectionSet,
            int from,
            int to)
        {
            if (from == to)
            {
                return false;
            }

            // 無向グラフとして扱うため、順序を統一したキーを使う。
            var key = PairKey(from, to);
            if (!connectionSet.Add(key))
            {
                return false;
            }

            connections.Add(new SectionConnection(from, to));
            return true;
        }

        // 2つのintを順序無関係にまとめたキーにする。
        private static long PairKey(int a, int b)
        {
            var min = Math.Min(a, b);
            var max = Math.Max(a, b);
            return ((long)min << 32) | (uint)max;
        }

        // すべての隣接区域を接続する（格子型に寄せる）。
        private static List<SectionConnection> BuildAllAdjacentConnections(IReadOnlyList<SectionDefinition> sections)
        {
            var connections = new List<SectionConnection>();
            var connectionSet = new HashSet<long>();

            for (int i = 0; i < sections.Count; i++)
            {
                for (int j = i + 1; j < sections.Count; j++)
                {
                    if (!sections[i].Active || !sections[j].Active)
                    {
                        continue;
                    }

                    if (AreAdjacent(sections[i].Bounds, sections[j].Bounds))
                    {
                        AddConnection(connections, connectionSet, sections[i].Index, sections[j].Index);
                    }
                }
            }

            return connections;
        }

        // すべての部屋を床として掘る。
        private static void CarveRooms(Map map, IReadOnlyList<MapRect> rooms)
        {
            for (int i = 0; i < rooms.Count; i++)
            {
                CarveRoom(map, rooms[i]);
            }
        }

        // 矩形範囲を床にする。
        private static void CarveRoom(Map map, MapRect room)
        {
            for (int x = room.Left; x <= room.Right; x++)
            {
                for (int y = room.Top; y <= room.Bottom; y++)
                {
                    map.SetTileType(new Position(x, y), TileType.Floor);
                }
            }
        }

        // 区域同士の接続情報に従って通路を掘る。
        private static void CarveCorridors(
            Map map,
            List<SectionState> sections,
            List<SectionConnection> connections,
            Random random)
        {
            // インデックスから区域状態を引けるようにする。
            var sectionLookup = new Dictionary<int, SectionState>();
            for (int i = 0; i < sections.Count; i++)
            {
                sectionLookup[sections[i].Definition.Index] = sections[i];
            }

            for (int i = 0; i < connections.Count; i++)
            {
                var connection = connections[i];
                if (!sectionLookup.TryGetValue(connection.From, out var fromSection))
                {
                    continue;
                }

                if (!sectionLookup.TryGetValue(connection.To, out var toSection))
                {
                    continue;
                }

                // 隣接区域の境界線上に C1/C2（境界点）を取得できない場合はスキップ。
                if (!TryGetBoundaryPoints(
                        fromSection.Definition.Bounds,
                        toSection.Definition.Bounds,
                        random,
                        out var boundaryFrom,
                        out var boundaryTo,
                        out var fromDirection,
                        out var toDirection))
                {
                    continue;
                }

                // 部屋の出口（Joint）か中継点（Relay）を通路の始点にする。
                var fromAnchor = GetAnchor(fromSection, fromDirection, random);
                var toAnchor = GetAnchor(toSection, toDirection, random);

                // 境界線が縦（左右接続）か横（上下接続）かで C1/C2 の取り方を分ける。
                if (fromDirection == Direction.East || fromDirection == Direction.West)
                {
                    // 左右に隣接しているケース：
                    // 1) 区域A -> C1（水平）
                    // 2) 区域B -> C2（水平）
                    // 3) C1 -> C2（垂直）
                    var boundaryX = boundaryFrom.X;
                    var c1 = new Position(boundaryX, fromAnchor.Y);
                    var c2 = new Position(boundaryX, toAnchor.Y);

                    CarveHorizontal(map, fromAnchor.X, c1.X, fromAnchor.Y);
                    CarveHorizontal(map, toAnchor.X, c2.X, toAnchor.Y);
                    CarveVertical(map, c1.Y, c2.Y, boundaryX);
                }
                else
                {
                    // 上下に隣接しているケース：
                    // 1) 区域A -> C1（垂直）
                    // 2) 区域B -> C2（垂直）
                    // 3) C1 -> C2（水平）
                    var boundaryY = boundaryFrom.Y;
                    var c1 = new Position(fromAnchor.X, boundaryY);
                    var c2 = new Position(toAnchor.X, boundaryY);

                    CarveVertical(map, fromAnchor.Y, c1.Y, fromAnchor.X);
                    CarveVertical(map, toAnchor.Y, c2.Y, toAnchor.X);
                    CarveHorizontal(map, c1.X, c2.X, boundaryY);
                }
            }
        }

        // 部屋の出口（Joint）または中継点（Relay）を通路の起点にする。
        private static Position GetAnchor(SectionState section, Direction direction, Random random)
        {
            if (section.Room.HasValue && section.Joints != null)
            {
                var room = section.Room.Value;
                return section.Joints.Pop(direction, room.Center, random);
            }

            return section.RelayPoint;
        }

        // 隣接する2区域の境界線上にある C1/C2 を返す（境界線に垂直な方向も返す）。
        private static bool TryGetBoundaryPoints(
            MapRect a,
            MapRect b,
            Random random,
            out Position boundaryA,
            out Position boundaryB,
            out Direction directionA,
            out Direction directionB)
        {
            // 左右に隣接している場合（Aが左、Bが右）。
            if (a.Right + 1 == b.Left && RangesOverlap(a.Top, a.Bottom, b.Top, b.Bottom))
            {
                var y = RandomInset(random, Math.Max(a.Top, b.Top), Math.Min(a.Bottom, b.Bottom));
                boundaryA = new Position(a.Right, y);
                boundaryB = new Position(b.Left, y);
                directionA = Direction.East;
                directionB = Direction.West;
                return true;
            }

            // 左右に隣接している場合（Bが左、Aが右）。
            if (b.Right + 1 == a.Left && RangesOverlap(a.Top, a.Bottom, b.Top, b.Bottom))
            {
                var y = RandomInset(random, Math.Max(a.Top, b.Top), Math.Min(a.Bottom, b.Bottom));
                boundaryA = new Position(a.Left, y);
                boundaryB = new Position(b.Right, y);
                directionA = Direction.West;
                directionB = Direction.East;
                return true;
            }

            // 上下に隣接している場合（Aが上、Bが下）。
            if (a.Bottom + 1 == b.Top && RangesOverlap(a.Left, a.Right, b.Left, b.Right))
            {
                var x = RandomInset(random, Math.Max(a.Left, b.Left), Math.Min(a.Right, b.Right));
                boundaryA = new Position(x, a.Bottom);
                boundaryB = new Position(x, b.Top);
                directionA = Direction.South;
                directionB = Direction.North;
                return true;
            }

            // 上下に隣接している場合（Bが上、Aが下）。
            if (b.Bottom + 1 == a.Top && RangesOverlap(a.Left, a.Right, b.Left, b.Right))
            {
                var x = RandomInset(random, Math.Max(a.Left, b.Left), Math.Min(a.Right, b.Right));
                boundaryA = new Position(x, a.Top);
                boundaryB = new Position(x, b.Bottom);
                directionA = Direction.North;
                directionB = Direction.South;
                return true;
            }

            boundaryA = default;
            boundaryB = default;
            directionA = Direction.North;
            directionB = Direction.South;
            return false;
        }

        // 境界端を避けたランダム値を返す（端から1マス内側に寄せる）。
        private static int RandomInset(Random random, int minInclusive, int maxInclusive)
        {
            if (maxInclusive - minInclusive >= 2)
            {
                minInclusive++;
                maxInclusive--;
            }

            if (maxInclusive < minInclusive)
            {
                return minInclusive;
            }

            return random.Next(minInclusive, maxInclusive + 1);
        }

        // 2つの区間が重なっているかを判定する。
        private static bool RangesOverlap(int minA, int maxA, int minB, int maxB)
        {
            return Math.Max(minA, minB) <= Math.Min(maxA, maxB);
        }

        // 矩形を内側に縮める（余白確保用）。
        private static MapRect ShrinkRect(MapRect rect, int padding)
        {
            if (padding <= 0)
            {
                return rect;
            }

            var width = rect.Width - padding * 2;
            var height = rect.Height - padding * 2;
            if (width <= 0 || height <= 0)
            {
                return rect;
            }

            return new MapRect(rect.X + padding, rect.Y + padding, width, height);
        }

        // 水平方向の直線通路を掘る。
        private static void CarveHorizontal(Map map, int x1, int x2, int y)
        {
            var start = Math.Min(x1, x2);
            var end = Math.Max(x1, x2);
            for (int x = start; x <= end; x++)
            {
                map.SetTileType(new Position(x, y), TileType.Floor);
            }
        }

        // 垂直方向の直線通路を掘る。
        private static void CarveVertical(Map map, int y1, int y2, int x)
        {
            var start = Math.Min(y1, y2);
            var end = Math.Max(y1, y2);
            for (int y = start; y <= end; y++)
            {
                map.SetTileType(new Position(x, y), TileType.Floor);
            }
        }

        // 生成が失敗した場合の保険部屋を中央に作る。
        private static MapRect CreateFallbackRoom(int width, int height)
        {
            var roomWidth = Math.Min(DefaultMaxRoomSize, Math.Max(DefaultMinRoomSize, width / 4));
            var roomHeight = Math.Min(DefaultMaxRoomSize, Math.Max(DefaultMinRoomSize, height / 4));
            var roomX = Math.Max(1, (width - roomWidth) / 2);
            var roomY = Math.Max(1, (height - roomHeight) / 2);
            return new MapRect(roomX, roomY, roomWidth, roomHeight);
        }

        // スタートから一番遠い床（まず部屋中心、次に全床）を探す。
        private static Position FindFarthestWalkable(Map map, Position start, IReadOnlyList<MapRect> rooms)
        {
            var farthest = start;
            var maxDistance = -1;

            for (int i = 0; i < rooms.Count; i++)
            {
                var center = rooms[i].Center;
                var distance = Manhattan(start, center);
                if (distance > maxDistance)
                {
                    maxDistance = distance;
                    farthest = center;
                }
            }

            if (farthest != start)
            {
                return farthest;
            }

            foreach (var position in map.AllPositions())
            {
                if (!map.IsWalkable(position) || position == start)
                {
                    continue;
                }

                var distance = Manhattan(start, position);
                if (distance > maxDistance)
                {
                    maxDistance = distance;
                    farthest = position;
                }
            }

            return farthest;
        }

        // マンハッタン距離（縦横移動の合計距離）。
        private static int Manhattan(Position a, Position b)
        {
            return Math.Abs(a.X - b.X) + Math.Abs(a.Y - b.Y);
        }
    }
}


